# Smart PR-Agent Configuration with Auto-Approval

[config]
model = "anthropic/claude-3-5-sonnet-20241022"
fallback_models = ["anthropic/claude-3-opus-20240229", "anthropic/claude-3-haiku-20240307"]
temperature = 0.2
max_tokens = 8192
publish_output = true

# Enable smart auto-approval
enable_auto_approval = true

# Custom auto-approval thresholds (adjust to your preferences)
auto_approve_confidence_threshold = 85    # AI confidence (1-100)
auto_approve_complexity_threshold = 5     # Max complexity (1-10)
auto_approve_security_threshold = 8       # Min security score (1-10)
auto_approve_effort_threshold = 3         # Max effort score (1-5)
auto_approve_max_files = 5               # Max files changed
auto_approve_max_lines = 200             # Max total lines changed
auto_approve_max_issues = 3              # Max issues found

[pr_reviewer]
# Enable custom scoring features
require_estimate_effort_to_review = true
require_security_review = true
require_tests_review = true
require_score_review = false

# Review settings
num_max_findings = 5
persistent_comment = true
enable_review_labels_effort = true
enable_review_labels_security = true

# Custom instructions for better auto-approval analysis
extra_instructions = """
Focus on providing accurate confidence, complexity, and security scores.
- Confidence: How certain are you about your analysis?
- Complexity: How difficult is this code to understand and maintain?
- Security: How safe is this code from security vulnerabilities?
- Auto-approval: Only recommend for very safe, straightforward changes.
"""
