# Smart PR-Agent Configuration

[config]
# Use Claude Sonnet 4 exclusively for optimal PR review performance
model = "anthropic/claude-sonnet-4-20250514"
fallback_models = []



# ⚠️ TESTING ONLY: Force override bypasses all safety checks!
# auto_approve_force_override = true  # FORCE APPROVAL ENABLED - Testing mode!

[github_action_config]
# Opt-in trigger: PR-Agent will only run if ##aidesc is found in PR description
require_aidesc_trigger = true
