# Example PR-Agent configuration for dry-run mode
# This configuration enables read-only mode where all comments are printed to console

[config]
# Enable dry-run mode - all publishing operations will print to console instead
dry_run = true

# You can still configure other settings as normal
publish_output = true
verbosity_level = 0

[pr_reviewer]
# Review settings work as normal, but output goes to console
num_max_findings = 5
require_tests_review = true
require_estimate_effort_to_review = true

[pr_code_suggestions]
# Code suggestions will be displayed in console
num_code_suggestions_per_chunk = 4 