name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for git tags
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Run build and push script
      id: build
      run: |
        chmod +x scripts/build-and-push.sh
        scripts/build-and-push.sh
    
    - name: Extract version components
      id: version
      run: |
        VERSION=${{ steps.build.outputs.new_version }}
        # Remove 'v' prefix and split into components
        VERSION_NUM=${VERSION#v}
        MAJOR=$(echo $VERSION_NUM | cut -d. -f1)
        MINOR=$(echo $VERSION_NUM | cut -d. -f2)
        echo "major=v$MAJOR" >> $GITHUB_OUTPUT
        echo "minor=v$MAJOR.$MINOR" >> $GITHUB_OUTPUT
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.build.outputs.new_version }}
        release_name: ${{ steps.build.outputs.new_version }}
        body: |
          ${{ github.event.pull_request.title || github.event.head_commit.message }}
          
          ## Docker Images
          - `ghcr.io/jacsamell/github-pr-bot:latest`
          - `ghcr.io/jacsamell/github-pr-bot:${{ steps.build.outputs.new_version }}`
          - `ghcr.io/jacsamell/github-pr-bot:${{ steps.version.outputs.major }}`
          - `ghcr.io/jacsamell/github-pr-bot:${{ steps.version.outputs.minor }}`
          
          ## Usage
          ```yaml
          uses: docker://ghcr.io/jacsamell/github-pr-bot:${{ steps.build.outputs.new_version }}
          ```
        draft: false
        prerelease: false 