name: PR Agent

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  pr-agent:
    uses: ./.github/workflows/pr-agent-reusable.yml
    with:
      auto_review: true
      auto_describe: true
      auto_improve: false
      enable_auto_approval: true
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }} 