name: PR Agent Reusable Workflow

on:
  workflow_call:
    inputs:
      model:
        description: 'AI model to use'
        required: false
        default: 'anthropic/claude-sonnet-4-20250514'
        type: string
      enable_auto_approval:
        description: 'Enable auto-approval'
        required: false
        default: false
        type: boolean
      max_findings:
        description: 'Maximum number of findings'
        required: false
        default: 5
        type: number
      auto_review:
        description: 'Enable auto review'
        required: false
        default: true
        type: boolean
      auto_describe:
        description: 'Enable auto description'
        required: false
        default: false
        type: boolean
      auto_improve:
        description: 'Enable auto code suggestions (separate tool - now integrated into review)'
        required: false
        default: false
        type: boolean
    secrets:
      ANTHROPIC_API_KEY:
        description: 'Anthropic API key'
        required: true

jobs:
  pr-agent:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    
    steps:
    - name: PR Agent
      uses: docker://jacsamell/pr-agent:v1
      env:
        # GitHub Action environment variables
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        GITHUB_TOKEN: ${{ github.token }}
        # API Keys
        ANTHROPIC__KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        # Configuration
        CONFIG.MODEL: ${{ inputs.model }}
        CONFIG.ENABLE_AUTO_APPROVAL: ${{ inputs.enable_auto_approval }}
        CONFIG.MAX_MODEL_TOKENS: "100000"
        PR_REVIEWER.PERSISTENT_COMMENT: "true"
        PR_REVIEWER.NUM_MAX_FINDINGS: ${{ inputs.max_findings }}
        # Task configuration
        GITHUB_ACTION_CONFIG.AUTO_REVIEW: ${{ inputs.auto_review }}
        GITHUB_ACTION_CONFIG.AUTO_DESCRIBE: ${{ inputs.auto_describe }}
        GITHUB_ACTION_CONFIG.AUTO_IMPROVE: ${{ inputs.auto_improve }}