name: GitHub PR Bot

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

concurrency:
  group: pr-bot-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  pr-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: GitHub PR Bot Analysis
      uses: ./
      with:
        anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        github_token: ${{ github.token }}
        model: 'anthropic/claude-sonnet-4-20250514'
        enable_auto_approval: true
        auto_review: true
        auto_describe: false
        auto_improve: false
        max_model_tokens: '100000'
        require_trigger: false
        max_findings: 5
        pretty_logs: true