name: GitHub PR Bot Reusable Workflow

on:
  workflow_call:
    inputs:
      model:
        description: 'AI model to use for PR analysis'
        required: false
        default: 'anthropic/claude-sonnet-4-20250514'
        type: string
      enable_auto_approval:
        description: 'Enable automatic PR approval for safe changes'
        required: false
        default: true
        type: boolean
      max_findings:
        description: 'Maximum number of review findings to report'
        required: false
        default: 8
        type: number
      auto_review:
        description: 'Automatically review PRs'
        required: false
        default: true
        type: boolean
      auto_describe:
        description: 'Automatically generate PR descriptions'
        required: false
        default: true
        type: boolean
      auto_improve:
        description: 'Automatically suggest code improvements'
        required: false
        default: true
        type: boolean
      pretty_logs:
        description: 'Enable pretty console logs instead of JSON'
        required: false
        default: true
        type: boolean
    secrets:
      ANTHROPIC_API_KEY:
        description: 'Anthropic API key for Claude access'
        required: true

jobs:
  pr-bot:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub PR Bot Analysis
      uses: docker://ghcr.io/jacsamell/github-pr-bot:latest
      env:
        # GitHub Action environment
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        GITHUB_TOKEN: ${{ github.token }}
        
        # API Configuration
        ANTHROPIC__KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        
        # Core Configuration
        CONFIG.MODEL: ${{ inputs.model }}
        CONFIG.ENABLE_AUTO_APPROVAL: ${{ inputs.enable_auto_approval }}
        CONFIG.MAX_MODEL_TOKENS: "100000"
        
        # Review Configuration
        PR_REVIEWER.PERSISTENT_COMMENT: "true"
        PR_REVIEWER.NUM_MAX_FINDINGS: ${{ inputs.max_findings }}
        
        # Auto-Action Configuration
        GITHUB_ACTION_CONFIG.AUTO_REVIEW: ${{ inputs.auto_review }}
        GITHUB_ACTION_CONFIG.AUTO_DESCRIBE: ${{ inputs.auto_describe }}
        GITHUB_ACTION_CONFIG.AUTO_IMPROVE: ${{ inputs.auto_improve }}
        GITHUB_ACTION_CONFIG.ENABLE_OUTPUT: "true"
        
        # Logging Configuration
        GITHUB_ACTION_CONFIG.PRETTY_LOGS: ${{ inputs.pretty_logs }}