name: GitHub PR Bot

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  pr-bot:
    uses: ./.github/workflows/pr-bot-reusable.yml
    with:
      auto_review: true
      auto_describe: true
      auto_improve: false
      enable_auto_approval: true
      max_findings: 8
      pretty_logs: true
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}