name: GitHub PR Bot

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

concurrency:
  group: pr-bot-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  pr-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: GitHub PR Bot Analysis
      uses: ./

      with:
        anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        auto_review: true
        enable_auto_approval: true
        enable_review_labels_effort: true
        enable_review_labels_security: true