name: GitHub PR Bot

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

concurrency:
  group: pr-bot-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  pr-bot:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub PR Bot Analysis
      uses: jacsamell/github-pr-bot@v1.0.0
      with:
        anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        auto_review: true
        enable_auto_approval: true